### PR TITLE
fix(dev-env): Do not use a temporary directory for Lando

### LINKED ISSUE #1191: SSL certificate is not verified inside dev environment
I'm using VIP dev-env for a project, and noticing that the SSL cvertificate is not verified inside the dev environment. I can access the site over https from my host machine after accepting the security exception, but when making https requests inside the container, they always fail with the error message

```
cURL error 60: SSL certificate problem: unable to get local issuer certificate
```
The [Lando docs](https://docs.lando.dev/config/security.html#trusting-the-ca) seem to say that by default Lando should be automatically trusting the CA internally:

> While Lando will automatically trust this CA internally, it is up to you to trust it on your host machine. Doing so will alleviate browser warnings regarding certs we issue.

I notice that vip dev-env specifies a custom path for the Lando config which is inside the temp directory `/tmp/lando` as opposed to `~/.lando` which could be related. In any case, it means that the certificate is regenerated every time the container is started, which makes it more difficult to trust on the host machine.

I'm wondering if there's a workaround for this, or what it would take to fix this behavior?
 
---

## Expected/Desired Behavior

After starting a dev environment with `vip dev-env start`, the ssl certificate for all domains served by the site should be automatically trusted inside the PHP container, so that REST requests can work without setting `sslverify => false`. 

## Actual Behavior

Making REST requests from application code to the same site fail with a cURL SSL certificate problem, unless the sslverify option is set to false. 

## (Optional) Additional notes

System: Ubuntu 22.04
VIP-CLI version: 2.23.0
Node version: 16.18.1

### PR DESCRIPTION
**Pull request by sjinks**
## Description

Related: #1191, #1198

This PR updates Lando configuration so that Lando's configuration perists reboots. Among other things (like faster warm bootstrap), this allows us to use the same certificate authority for all development environments, eliminating the need to trust the CA every time `/tmp/lando` disappears.

## Steps to Test

1. Create and start a test environment; stop it.
2. Apply the patch and start the test environment again; it should work.

*NB:* it may be necessary to restart all running environments after applying the patch.

### CODE REVIEW

File: src/lib/dev-environment/dev-environment-lando.js [hunk 1]
```diff
@@ -54,6 +44,16 @@ function getLandoConfig() {
...
 
+	const vipDir = path.join( xdgBasedir.data || os.tmpdir(), 'vip' );
+	const landoDir = path.join( vipDir, 'lando' );
+	const fakeHomeDir = path.join( landoDir, 'home' );
+
+	try {
+		await fs.promises.mkdir( fakeHomeDir, { recursive: true } );
+	} catch ( err ) {
+		// Ignore
+	}
```
Comment (sjinks) [inline src/lib/dev-environment/dev-environment-lando.js:54]: We do this to be compatible with `@lando/core` - until they accept our patch, at least.

File: src/lib/dev-environment/dev-environment-lando.js [hunk 2]
```diff
@@ -108,8 +108,9 @@ function getLandoConfig() {
 			'@lando/wordpress',
 		],
 		proxyName: 'vip-dev-env-proxy',
-		userConfRoot: getLandoUserConfigurationRoot(),
-		home: '',
+		userConfRoot: landoDir,
+		home: fakeHomeDir,
+		domain: 'lndo.site',
```
Comment (sjinks) [inline src/lib/dev-environment/dev-environment-lando.js:112]: The `domain` key is used to name the certificate file; if we don't pass it, we'll get `undefined.pem`, which is a bit confusing.

File: src/lib/dev-environment/dev-environment-lando.js (hunk 1 above)
Comment (rinatkhaziev) [reply src/lib/dev-environment/dev-environment-lando.js:54]: What's a fakeHomeDir?

Comment (sjinks) [reply src/lib/dev-environment/dev-environment-lando.js:54]: Empty directory to be mounted as `/home`. `@lando/core` will create the `.ssh` directory inside it. If we pass an empty string as `home` (see below), Lando will create `.ssh` directory in the current directory, which is not what we want.

In brief, we are trying to solve here the issue we solved in https://github.com/Automattic/lando-cli/pull/15, except that we don't want to fork `@lando/core`.

**Review by rinatkhaziev — APPROVED** [review]
